### ISSUE TITLE
A way to change video on the fly?

### ISSUE THREAD

**Issue by mooseh** [tserkov/vue-twitch-player#2]
hey nice wrapper for vue

I tried changing the data but it doesn't change the video, is there a way to change the video?

Thanks

**Comment by tserkov** [comment]
Can you show me how you're trying to use the component? The channel, collection, and video parameters are all placed on watch.

**Comment by mooseh** [comment]
yep no problem.

im using the compnent inside of another component

app.js 
```
import VideoIndex from './components/videos/VideoIndex.vue';
import Twitch from 'vue-twitch-player'
Vue.component('video-index', VideoIndex);
Vue.component('twitch-player', Twitch);

```

VideoIndex.vue (essential snippets)

```
<twitch-player class="video-play" :video="first.provider_id"></twitch-player>

<div v-for="video in videos" @click="loadVideo($event, video)" class="col-12 col-sm-6 col-md-3">

        methods: {
            loadVideo(event, video) {
                console.log(video);
                this.first = video;
            }
        },

```

Hope this makes sense.

Kind Regards
MooseH

**Comment by tserkov** [comment]
It looks like you've run into one of Vue's [Change Detection Caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats). Namely, you can't assign an Object to a root data element. You'll need to do something like this:
```javascript
loadVideo(event, video) {
  console.log(video);
  this.$set(this, 'first', video);
}
```
