### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by maude2010** [tserkov/vue-twitch-player#4]
after installation vue-twitch-player, and complet "main.js" and "template" , I have error message : "Failed to compile.

./src/components/StreamPage.vue
Module Error (from ./node_modules/eslint-loader/index.js):

/var/www/html/o-game/O-game-frontend/app/src/components/StreamPage.vue
  13:7  error  The "VueTwitchPlayer" component has been registered but not used  vue/no-unused-components

✖ 1 problem (1 error, 0 warnings)"
I use Vue.Js version 4.4.6

thank you

**Comment by tserkov** [comment]
> The "VueTwitchPlayer" component has been registered but not used vue/no-unused-components

That error tells you exactly what's happened -- you've imported the component, but haven't used it in the template.

Please review the Usage part of the readme: https://github.com/tserkov/vue-twitch-player#use

**Comment by maude2010** [comment]
yes i use the component in my page :
```
 <template>
  <twitch-player
    :video="video"
  ></twitch-player>
</template>

<script>
  import VueTwitchPlayer from 'vue-twitch-player';

  export default {
    // ...
    components: {
      VueTwitchPlayer,
    },
    data() {
      return {
        video: '117216248',
      };
    },
    // ...
  };
</script>
```
